name: ZizonPlugin
version: 1.0
main: com.zz.ZizonPlugin.ZizonPlugin
api-version: 1.16
commands:
  zizon:
    description: zl존 개쩌는 커맨드입니다.
    usage: /zizon
  lightning:
    description: 바라보는 방향에 우르르쾅쾅을 시전합니다.
    usage: /lightning
    aliases:
      - 우르르쾅쾅
      - 백만볼트
  explode:
    description: 바라보는 방향으로 zl존 개쩌는 김순상의 초고출력을 시전합니다.
    usage: /explode
    aliases:
      - 초고출력
      - 순상
      - sunsang
  chichiya:
    description: 바라보는 방향으로 zl존 개쩌는 64발의 화살을 발사합니다.
    usage: /chichiya
    aliases:
      - 용의천천시
      - 천천시
  helmetbreak:
    description: 바라보는 방향으로 10칸 이동 후, 이동 범위 내 있던 대상에 구속 효과 적용, 일정 시간 뒤에 폭발을 일으킵니다.
    usage: /helmetbreak
    aliases:
      - 투구깨기
  ganpa:
    description: 뒤로 5칸 이동을 하며 상대의 공격을 회피합니다. 회피의 성공할시 매우 강해집니다..
    usage: /ganpa
    aliases:
      - 간파