name: ZizonPlugin
version: 1.0
main: com.zz.ZizonPlugin.ZizonPlugin
api-version: 1.16
commands:
  zizon:
    description: zl존 개쩌는 커맨드입니다.
    usage: /zizon
  lightning:
    description: 바라보는 방향에 우르르쾅쾅을 시전합니다.
    usage: /lightning
    aliases:
      - 우르르쾅쾅
      - 백만볼트
  explode:
    description: 바라보는 방향으로 zl존 개쩌는 김순상의 초고출력을 시전합니다.
    usage: /explode
    aliases:
      - 초고출력
      - 순상
      - sunsang